name: glow_grid
description: "Light Switches Control App"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter_colorpicker: ^1.0.3
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  http: ^1.2.1
  sqflite: ^2.3.3+1
  fluttertoast: ^8.2.6
  path: ^1.9.0
  auto_size_text: ^3.0.0
#  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.5
  wifi_iot: ^0.3.19+2
  network_info_plus: ^6.0.1
  geolocator: ^13.0.3
  mobile_scanner: ^6.0.7
  flutter_iconpicker: ^4.0.1
  wifi_scan: ^0.4.1+2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
