// Dart core libraries
export 'dart:async';
export 'dart:convert';
export 'dart:io';
export 'dart:math';

// Flutter and third-party packages
export 'package:auto_size_text/auto_size_text.dart';
export 'package:connectivity_plus/connectivity_plus.dart' hide NetworkManagerClientFactory;
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_storage/firebase_storage.dart';
// export 'package:firebase_analytics/firebase_analytics.dart';
export 'package:flutter/material.dart';
export 'package:flutter/cupertino.dart' hide RefreshCallback;
export 'package:flutter/services.dart';
export 'package:flutter_colorpicker/flutter_colorpicker.dart';
export 'package:fluttertoast/fluttertoast.dart';
export 'package:get_storage/get_storage.dart';
export 'package:path/path.dart' hide context;
export 'package:path_provider/path_provider.dart';
export 'package:provider/provider.dart';
export 'package:qr_flutter/qr_flutter.dart';
export 'package:mobile_scanner/mobile_scanner.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:sqflite/sqflite.dart';
export 'package:wifi_scan/wifi_scan.dart';
export 'package:geolocator/geolocator.dart';
export 'package:flutter_iconpicker/flutter_iconpicker.dart';
export 'package:collection/collection.dart';

// Project-specific imports
export 'constants/constants.dart';
export 'data/database_helper.dart';
export 'data/apartment_db.dart';
export 'data/room_db.dart';
export 'data/device_db.dart';
export 'data/export_db.dart';
export 'model/room_icon_data.dart';
export 'model/faq_item.dart';
export 'model/device_status.dart';
export 'commons.dart';
export 'glow_grid.dart';
export 'firebase_options.dart';
export 'screens/device_configuration_screen.dart';
export 'screens/export_data_screen.dart';
export 'screens/firmware_updating_screen.dart';
export 'screens/import_data_screen.dart';
export 'screens/splash_screen.dart';
export 'screens/onboarding_screen.dart';
export 'screens/room_details_screen.dart';
export 'screens/rooms_screen.dart';
export 'screens/settings_screen.dart';
export 'screens/support_screen.dart';
export 'screens/qr_scanner_screen.dart';
export 'styles/colors.dart';
export 'styles/sizes.dart';
export 'styles/styles.dart';
export 'styles/themes.dart';
export 'utils/socket_manager.dart';
export 'utils/app_state.dart';
export 'utils/firebase_storage_util.dart';
export 'utils/device_util.dart';
export 'utils/firmware_util.dart';
export 'utils/network_util.dart';
export 'utils/ui_utils.dart';
export 'utils/utility.dart';
export 'utils/painter.dart';