name: iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2

    - name: Install dependencies
      run: |
        flutter pub get
        cd ios
        pod install
        cd ..

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: build/ios/iphoneos/
