name: iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS
        run: flutter build ios --release --no-codesign --no-tree-shake-icons